name = "zjdocker"
type = "webpack"
account_id = "988f26e5d1a71274200aef12e8e07633"
workers_dev = true
route = "dk.300111.xyz"
zone_id = "c178e758afdcfaa7591a36558a1e4088"
webpack_config = "webpack.config.js"
kv_namespaces = [
	 { binding = "vbpb", id = "11e46232b4004297a7818adaf9c5510b" }
]
