name = "zjdocker"
type = "webpack"
account_id = "988f26e5d1a71274200aef12e8e07633"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [
	 { binding = "vbpb", id = "11e46232b4004297a7818adaf9c5510b" }
]
